Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/ESRB_Rating__c.field-meta.xml
<CustomField>
    <fullName>ESRB_Rating__c</fullName>
    <label>ESRB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ESRB_Ratings</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Game_Approval__c.field-meta.xml
<CustomField>
    <fullName>Game_Approval__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Game Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Game_Description__c.field-meta.xml
<CustomField>
    <fullName>Game_Description__c</fullName>
    <label>Game Description</label>
    <type>TextArea</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 0/force-app/main/default/objects/Game_Account__c/Game_Account__c.object-meta.xml
<CustomObject>
    <label>Game Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Account__c/fields/Account_Password__c.field-meta.xml
<CustomField>
    <fullName>Account_Password__c</fullName>
    <label>Account Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <defaultValue>&quot;Gamer&quot;</defaultValue>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gamer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/force-app/main/default/objects/Game_Orders__c/Game_Orders__c.object-meta.xml
<CustomObject>
    <label>Game Order</label>
    <nameField>
        <displayFormat>GameOrder-{00000000}</displayFormat>
        <label>Game Orders ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Orders__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Game Orders</relationshipLabel>
    <relationshipName>GameOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Orders__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipLabel>Game Orders</relationshipLabel>
    <relationshipName>GameOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Orders__c/fields/Game_Payment__c.field-meta.xml
<CustomField>
    <fullName>Game_Payment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Game Payment</label>
    <referenceTo>Game_Payment__c</referenceTo>
    <relationshipLabel>Game Orders</relationshipLabel>
    <relationshipName>Game_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project 0/force-app/main/default/objects/Game_Payment__c/Game_Payment__c.object-meta.xml
<CustomObject>
    <label>Game Payment</label>
    <nameField>
        <label>Game Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>CardType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Cards</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card_Holder__c.field-meta.xml
<CustomField>
    <fullName>Card_Holder__c</fullName>
    <label>Card Holder</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game_Account__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipLabel>Game Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Card_Holder_Name__c</fullName>
    <label>Card Holder Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>20</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card_Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Card_Security_Code__c</fullName>
    <label>Card Security Code</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Month__c</fullName>
    <label>Expiration Month</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Payment__c/fields/Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Year__c</fullName>
    <label>Expiration Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/My_Games__c.object-meta.xml
<CustomObject>
    <label>My Game</label>
    <nameField>
        <label>Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/ESRB_Rating__c.field-meta.xml
<CustomField>
    <fullName>ESRB_Rating__c</fullName>
    <label>ESRB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ESRB_Ratings</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>My Games</relationshipLabel>
    <relationshipName>My_Games</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipName>Game_Libraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Description__c.field-meta.xml
<CustomField>
    <fullName>Game_Description__c</fullName>
    <label>Game Description</label>
    <type>TextArea</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Genre__c.field-meta.xml
<CustomField>
    <fullName>Game_Genre__c</fullName>
    <label>Game Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Title__c.field-meta.xml
<CustomField>
    <fullName>Game_Title__c</fullName>
    <label>Game Title</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/ESRB_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RP (Rating Pending)</fullName>
        <default>true</default>
        <label>RP (Rating Pending)</label>
    </customValue>
    <customValue>
        <fullName>E (Everyone)</fullName>
    </customValue>
    <customValue>
        <fullName>E10+ (Everyone 10+)</fullName>
    </customValue>
    <customValue>
        <fullName>T (Teen)</fullName>
    </customValue>
    <customValue>
        <fullName>M (Mature)</fullName>
    </customValue>
    <customValue>
        <fullName>AO (Adult Only)</fullName>
    </customValue>
    <masterLabel>ESRB Ratings</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/globalValueSets/Payment_Cards.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visa</fullName>
    </customValue>
    <customValue>
        <fullName>Mastercard</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <customValue>
        <fullName>American Express</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Payment Cards</masterLabel>
</GlobalValueSet>

Project 0/force-app/main/default/classes/gameLibraryTest.cls
@isTest
public class gameLibraryTest {
	@testSetup
    public static void getRec(){
        //create Game Account
        Game_Account__c acc = new Game_Account__c (Name = 'myTest', Account_Password__c ='123456', Account_Type__c ='Gamer', 
                                                   Date_Of_Birth__c =Date.newInstance(1990, 04, 04), Email__c='testemail@test.com');
        //Game_Account__c acc2 = new Game_Account__c (Name = 'myTest1', Account_Password__c ='123456', Account_Type__c ='Gamer', 
                                                   //Date_Of_Birth__c =Date.newInstance(1990, 04, 04), Email__c='testemai1l@test.com');
        insert acc;
        
        
        
        
        //insert acc2;
        //get the acc Id
        Game_Account__c myAcc = [SELECT Name FROM Game_Account__c WHERE Name='myTest'];
        
        Game_Payment__c pay = new Game_Payment__c(Name='AAA', Card_Holder__c=myAcc.Id, Card_Holder_Name__c='agfasdas', Card_Number__c='1234-4569-7894-4654', 
                                                  Card_Security_Code__c='123', Card_Type__c='Credit Card', Card__c='Visa',Expiration_Month__c='05', Expiration_Year__c='2022');
        insert pay;
        
        //Game_Account__c myAcc2 = [SELECT Name FROM Game_Account__c WHERE Name='myTest1'];
        //add game
        //
        List<Game__c> tempGameList = new List<Game__c>();
        for(Integer i=0; i<10; i++){
            Game__c game = new Game__c(Name = 'Test Game'+i, Game_Description__c ='DKASJDNAKSJD', Developer__c='Dev '+i, Genre__c='Survival',
                                      Publisher__c='Publisher '+i, Release_Date__c =System.today(), ESRB_Rating__c='T (Teen)', Game_Approval__c='Accepted', Price__c=100+i);
            tempGameList.add(game);
        }
        insert tempGameList;
        Game_Payment__c payment = [SELECT Id FROM Game_Payment__c LIMIT 1];
        List<Game__c> gameList = [SELECT Name, Genre__c FROM Game__c];
        //add to game library
        List<My_Games__c> myGames = new List<My_Games__c>();
        List<Game_Orders__c> gameOr = new List<Game_Orders__c>();
        for(Integer i =0; i<gameList.size(); i++){
            My_Games__c temp = new My_Games__c(Name = gameList[i].Name, Game__c=gameList[i].Id, Game_Genre__c = gameList[i].Genre__c,
                                               Game_Title__c=gameList[i].Name, Game_Account__c = myAcc.Id);
            myGames.add(temp);
            
        }
        Game__c myG = [SELECT Name, Genre__c FROM Game__c WHERE Name='Test Game1'];
   		My_Games__c temp11 = new My_Games__c(Name = 'Test Game1', Game__c=myG.Id, Game_Genre__c = myG.Genre__c, Game_Title__c='asdasd', Game_Account__c = myAcc.Id);
        myGames.add(temp11);
        insert myGames;
        Game_Orders__c temp1 = new Game_Orders__c(Game_Account__c = myAcc.Id, Game_Payment__c = payment.Id, Game__c=myG.Id);
        insert temp1;
        
    }
    
    @isTest
    public static void mytest(){
        Test.startTest();
        Game_Account__c myAcc = [SELECT Name FROM Game_Account__c WHERE Name='myTest' LIMIT 1];
        //List<My_Games__c> myGames = [SELECT Name FROM My_Games__c WHERE Game_Account__c =: myAcc.Id];
        List<Game__c> myGames = gameLibraryController.getMyGame();
        Test.stopTest();
        System.assertEquals(10, myGames.size());
        
    }
    
    @isTest
    public static void testMostPopular(){
       Test.startTest();
       	List<Game__c> myGames = gameLibraryController.getMostPopularGame();
        List<My_Games__c> check = [SELECT Name FROM My_Games__c];
        Test.stopTest();
        System.assertEquals('Test Game1', myGames[0].Name);
    }
    
    @isTest
    public static void testBuyGame(){
        Test.startTest();
        Game__c game = new Game__c(Name = 'Test Game 00', Game_Description__c ='DKASJDNAKSJD', Developer__c='Dev ',
                                   Genre__c='Survival', Publisher__c='Publisher ', Release_Date__c =System.today(), ESRB_Rating__c='T (Teen)', Game_Approval__c='Accepted', Price__c=100);
        insert game;
        Game__c myGame = [SELECT Name, Genre__c FROM Game__c WHERE Name='Test Game 00'];
        System.debug(myGame);
        Boolean check = gameLibraryController.buyPopularGame(myGame);
        
        System.assertNotEquals(true, check);
        Boolean fcheck = gameLibraryController.buyPopularGame(myGame);
        System.assertEquals(true, fcheck);
        Test.stopTest();
    }
}