Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/ESRB_Rating__c.field-meta.xml
<CustomField>
    <fullName>ESRB_Rating__c</fullName>
    <label>ESRB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ESRB_Ratings</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 0/force-app/main/default/objects/Game_Account__c/Game_Account__c.object-meta.xml
<CustomObject>
    <label>Game Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Account__c/fields/Account_Password__c.field-meta.xml
<CustomField>
    <fullName>Account_Password__c</fullName>
    <label>Account Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <defaultValue>&quot;Gamer&quot;</defaultValue>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gamer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 0/force-app/main/default/objects/Game_Account__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/Wishlist__c.object-meta.xml
<CustomObject>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>WL-{0000}</displayFormat>
        <label>Wishlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Wishlists</relationshipLabel>
    <relationshipName>Wishlists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipLabel>Wishlists</relationshipLabel>
    <relationshipName>Wishlists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <formula>IF ( INCLUDES ( Game__r.Genre__c , &quot;RTS (Real-time strategy)&quot; ), &quot;RTS (Real-time strategy); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;RPG (Role Playing Game)&quot; ), &quot;RPG (Role Playing Game); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Simulation&quot; ), &quot;Simulation; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Platformer&quot; ), &quot;Platformer; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Survival&quot; ), &quot;Survival; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Horror&quot; ), &quot;Horror; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Crafting&quot; ), &quot;Crafting; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Sport&quot; ), &quot;Sport; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Action&quot; ), &quot;Action; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Adventure&quot; ), &quot;Adventure; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Fighting&quot; ), &quot;Fighting; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;FPS (First Person Shooter)&quot; ), &quot;FPS (First Person Shooter); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;MMO (Massive Multiplayer Online)&quot; ), &quot;MMO (Massive Multiplayer Online); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;MMORPG (Massive Multiplayer Online Role-Playing Game)&quot; ), &quot;MMORPG (Massive Multiplayer Online Role-Playing Game); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;MOBA (Multiplayer Online Battle Arena)&quot; ), &quot;MOBA (Multiplayer Online Battle Arena); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Multiplayer&quot; ), &quot;Multiplayer; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Party&quot; ), &quot;Party; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Puzzle&quot; ), &quot;Puzzle; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Racing&quot; ), &quot;Racing; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Rhythm&quot; ), &quot;Rhythm; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Stealth&quot; ), &quot;Stealth; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;TPS (Third Person Shooter)&quot; ), &quot;TPS (Third Person Shooter); &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Trivia&quot; ), &quot;Trivia; &quot;,null ) &amp;
IF ( INCLUDES ( Game__r.Genre__c , &quot;Strategy&quot; ), &quot;Strategy; &quot;,null )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Genre</label>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Game__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <formula>Game__r.Publisher__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Publisher</label>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Wishlist__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <formula>Game__r.Release_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/ESRB_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RP (Rating Pending)</fullName>
        <default>true</default>
        <label>RP (Rating Pending)</label>
    </customValue>
    <customValue>
        <fullName>E (Everyone)</fullName>
    </customValue>
    <customValue>
        <fullName>E10+ (Everyone 10+)</fullName>
    </customValue>
    <customValue>
        <fullName>T (Teen)</fullName>
    </customValue>
    <customValue>
        <fullName>M (Mature)</fullName>
    </customValue>
    <customValue>
        <fullName>AO (Adult Only)</fullName>
    </customValue>
    <masterLabel>ESRB Ratings</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/force-app/main/default/classes/AuraControllerTests.cls
@IsTest
public class AuraControllerTests {
	@TestSetup
    public static void testCreate(){
        Game__c g = new Game__c(
            Name='Test',
            Developer__c='Test',
            Publisher__c='Test',
            Genre__c='Sandbox',
            ESRB_Rating__c='E (Everyone)',
            Release_Date__c=system.today(),
            Price__c=10.00
        );
        
        Game_Account__c ga = new Game_Account__c(
            Name='testUser',
            Account_Password__c='test123',
            Password__c='test123',
            Account_Type__c='Gamer',
            Date_of_Birth__c=system.today(),
            Email__c='test@email.com'
        );
        
        insert g;
        insert ga;
        
        Wishlist__c w = new Wishlist__c(
        	Game_Account__c=ga.Id,
            Game__c=g.Id
        );
        insert w;    
    } 
    @IsTest
    public static void testGrabAccount(){
        Test.startTest();
        	Game_Account__c gaccTest = GameAccountAuraController.grabAccount('testUser','test123');
        	Game_Account__c badTest = GameAccountAuraController.grabAccount('dugfvseu','testsdfsf123');
        	
        Test.stopTest();
        system.assertEquals('testUser',gaccTest.Name);
        
    }
    
    @IsTest
    public static void testGetWishlist(){
        
        Test.startTest();
        	List<Game__c> wishTest = WishlistController.getWishlist('testUser');
        	List<Game__c> badTest = WishlistController.getWishlist('duewhfgweiyu');
        Test.stopTest();
        system.assertEquals('Test',wishTest[0].Name);
        
        
    }
    
   
}