Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/force-app/main/default/objects/Game_Account__c/Game_Account__c.object-meta.xml
<CustomObject>
    <label>Game Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/My_Games__c/My_Games__c.object-meta.xml
<CustomObject>
    <label>My Game</label>
    <nameField>
        <label>Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>My Games</relationshipLabel>
    <relationshipName>My_Games</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipName>Game_Libraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Genre__c.field-meta.xml
<CustomField>
    <fullName>Game_Genre__c</fullName>
    <label>Game Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Title__c.field-meta.xml
<CustomField>
    <fullName>Game_Title__c</fullName>
    <label>Game Title</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/force-app/main/default/classes/createMyGame.cls
public class createMyGame {
    public static void create(){
        List<Game__c> gameList = [SELECT Name, Genre__c FROM Game__c];
        Game_Account__c acc = [SELECT Name FROM Game_Account__c LIMIT 1];
        List<My_Games__c> myGames = new List<My_Games__c>();
        for(Integer i =1; i<3; i++){
            My_Games__c temp = new My_Games__c(Name = gameList[i-1].Name, Game__c=gameList[i-1].Id, Game_Genre__c = gameList[i-1].Genre__c,
                                               Game_Title__c=gameList[i-1].Name, Game_Account__c = acc.Id);
            myGames.add(temp);
        }
        insert myGames;
    }

}