Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/ESRB_Rating__c.field-meta.xml
<CustomField>
    <fullName>ESRB_Rating__c</fullName>
    <label>ESRB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ESRB_Ratings</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Reviews__c/Game_Reviews__c.object-meta.xml
<CustomObject>
    <label>Game Reviews</label>
    <nameField>
        <label>Review Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Reviews__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game_Reviews__c/fields/Game_Name__c.field-meta.xml
<CustomField>
    <fullName>Game_Name__c</fullName>
    <inlineHelpText>The name of the game that the review is for.</inlineHelpText>
    <label>Game Name</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Game Reviews</relationshipLabel>
    <relationshipName>Game_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Reviews__c/fields/User_Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>User_Star_Rating__c</fullName>
    <label>User Star Rating</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/ESRB_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RP (Rating Pending)</fullName>
        <default>true</default>
        <label>RP (Rating Pending)</label>
    </customValue>
    <customValue>
        <fullName>E (Everyone)</fullName>
    </customValue>
    <customValue>
        <fullName>E10+ (Everyone 10+)</fullName>
    </customValue>
    <customValue>
        <fullName>T (Teen)</fullName>
    </customValue>
    <customValue>
        <fullName>M (Mature)</fullName>
    </customValue>
    <customValue>
        <fullName>AO (Adult Only)</fullName>
    </customValue>
    <masterLabel>ESRB Ratings</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/classes/DeveloperTest.cls
@isTest
public class DeveloperTest {
    
    @testSetup static void setup() {
        
        List<Game__c> testGames = new List<Game__c>();
        for(Integer i=0;i<2;i++) {
            testGames.add(new Game__c(Name = 'TestGame'+i, ESRB_Rating__c='T (Teen)', Genre__c='Fighting', Developer__c='Test',Publisher__c='Test', Price__c=1, Release_Date__c=system.today()));
        }
        insert testGames;  
        
        Game_Reviews__c testReview = new Game_Reviews__c(
        	Name='TestReview',
            User_Star_Rating__c = 1,
            Review__c='Eh',
            Game_Name__c = testGames[0].Id
        );
        system.debug(testReview);
        insert testReview;
    }
	
    @isTest static void testDevGameListController() {
        Test.startTest();
        List<Game__c> testGameList = DevGameListController.getGames();
        Game__c testGame1 = DevGameListController.getSingleGame('TestGame1');
        Test.stopTest();
        System.assertEquals(true, testGameList.size() == 2);
        System.assertEquals('TestGame1', testGame1.Name);
    }
    
    @isTest static void testReviewSearchController() {
        Test.startTest();
        List<Game_Reviews__c> testGameReviews = ReviewSearchController.getReviews('TestGame0');
        system.debug(testGameReviews);
        Test.stopTest();
        System.assertEquals('Eh', testGameReviews[0].Review__c);
    }
}