Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/ESRB_Rating__c.field-meta.xml
<CustomField>
    <fullName>ESRB_Rating__c</fullName>
    <label>ESRB Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ESRB_Ratings</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Game_Description__c.field-meta.xml
<CustomField>
    <fullName>Game_Description__c</fullName>
    <label>Game Description</label>
    <type>TextArea</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/ESRB_Ratings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>RP (Rating Pending)</fullName>
        <default>true</default>
        <label>RP (Rating Pending)</label>
    </customValue>
    <customValue>
        <fullName>E (Everyone)</fullName>
    </customValue>
    <customValue>
        <fullName>E10+ (Everyone 10+)</fullName>
    </customValue>
    <customValue>
        <fullName>T (Teen)</fullName>
    </customValue>
    <customValue>
        <fullName>M (Mature)</fullName>
    </customValue>
    <customValue>
        <fullName>AO (Adult Only)</fullName>
    </customValue>
    <masterLabel>ESRB Ratings</masterLabel>
</GlobalValueSet>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/force-app/main/default/classes/gameIdRetrieverTest.cls
@isTest
public class gameIdRetrieverTest {
		
    @testSetup
    public static void newGame(){
     //create a game, query it, and use the id as the relationship field.
     Game__c newG = new Game__c(
     		Name = 'Saladmander',
         	Game_Description__c = 'A salad salamander.',
         	Developer__c = 'MoneyBag',
         	Publisher__c = 'Zony',
         	Genre__c = 'Multiplayer',
         	ESRB_Rating__c = 'T (Teen)',
         	Release_Date__c = date.parse('06/27/2021'),
         	Price__c = 22.99
         	
     );
        
      insert newG;
        
    }
    
    
    @isTest
    public static void searchGames(){
 
        Test.startTest();
        String userInput = GameIdRetriever.userInput;
        userInput = 'Saladmander';
        list<Game__c> gameMatches = GameIdRetriever.getGameMatch(userInput);
        
        String name = gameMatches[0].Name;
        Test.stopTest();
        
        system.assertEquals('Saladmander', name);
    }
    
    @isTest
    public static void showGames(){
        Test.startTest();
        list<Game__c> showG = GameIdRetriever.showAllGames();
        String games = showG[0].Name;
        Test.stopTest();

        system.assertEquals('Saladmander', games);
    }
}