Project 0/force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Game_Description__c.field-meta.xml
<CustomField>
    <fullName>Game_Description__c</fullName>
    <label>Game Description</label>
    <type>TextArea</type>
</CustomField>

Project 0/force-app/main/default/objects/Game__c/fields/Game_User_Rating__c.field-meta.xml
<CustomField>
    <fullName>Game_User_Rating__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Game User Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/force-app/main/default/objects/Game_Account__c/Game_Account__c.object-meta.xml
<CustomObject>
    <label>Game Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Game Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project 0/force-app/main/default/objects/Game_Orders__c/Game_Orders__c.object-meta.xml
<CustomObject>
    <label>Game Order</label>
    <nameField>
        <displayFormat>GameOrder-{00000000}</displayFormat>
        <label>Game Orders ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/Game_Orders__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Game Orders</relationshipLabel>
    <relationshipName>GameOrders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/Game_Orders__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipLabel>Game Orders</relationshipLabel>
    <relationshipName>GameOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/My_Games__c.object-meta.xml
<CustomObject>
    <label>My Game</label>
    <nameField>
        <label>Game</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>Developer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>My Games</relationshipLabel>
    <relationshipName>My_Games</relationshipName>
    <type>Lookup</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Account__c.field-meta.xml
<CustomField>
    <fullName>Game_Account__c</fullName>
    <label>Game Account</label>
    <referenceTo>Game_Account__c</referenceTo>
    <relationshipName>Game_Libraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Description__c.field-meta.xml
<CustomField>
    <fullName>Game_Description__c</fullName>
    <label>Game Description</label>
    <type>TextArea</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Genre__c.field-meta.xml
<CustomField>
    <fullName>Game_Genre__c</fullName>
    <label>Game Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Game_Genre</valueSetName>
    </valueSet>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Game_Title__c.field-meta.xml
<CustomField>
    <fullName>Game_Title__c</fullName>
    <label>Game Title</label>
    <length>90</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/objects/My_Games__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project 0/CustomPackage/main/default/globalValueSets/Game_Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sandbox</fullName>
    </customValue>
    <customValue>
        <fullName>RTS (Real-time strategy)</fullName>
    </customValue>
    <customValue>
        <fullName>RPG (Role Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>Simulation</fullName>
    </customValue>
    <customValue>
        <fullName>Platformer</fullName>
    </customValue>
    <customValue>
        <fullName>Survival</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Crafting</fullName>
    </customValue>
    <customValue>
        <fullName>Sport</fullName>
    </customValue>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>FPS (First Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>MMO (Massive Multiplayer Online)</fullName>
    </customValue>
    <customValue>
        <fullName>MMORPG (Massive Multiplayer Online Role-Playing Game)</fullName>
    </customValue>
    <customValue>
        <fullName>MOBA (Multiplayer Online Battle Arena)</fullName>
    </customValue>
    <customValue>
        <fullName>Multiplayer</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzle</fullName>
    </customValue>
    <customValue>
        <fullName>Racing</fullName>
    </customValue>
    <customValue>
        <fullName>Rhythm</fullName>
    </customValue>
    <customValue>
        <fullName>Stealth</fullName>
    </customValue>
    <customValue>
        <fullName>TPS (Third Person Shooter)</fullName>
    </customValue>
    <customValue>
        <fullName>Trivia</fullName>
    </customValue>
    <customValue>
        <fullName>Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Puzzlers</fullName>
        <isActive>false</isActive>
        <label>Puzzlers</label>
    </customValue>
    <masterLabel>Game Genre</masterLabel>
</GlobalValueSet>

Project 0/force-app/main/default/classes/gameLibraryController.cls
public with sharing class gameLibraryController {
    @AuraEnabled
    public static List<Game__c> getMyGame(){
        Game_Account__c myUser = [SELECT Id, Name, CreatedById, OwnerId  FROM Game_Account__c WHERE  OwnerId= :UserInfo.getUserID() LIMIT 1];
        List<My_Games__c> tempGameList = [SELECT Name,Game_Description__c, Developer__c,Publisher__c, Game__c, Game_Title__c FROM My_Games__c WHERE Game_Account__c =: myUser.id];
        List<My_Games__c> gameList =(List<My_Games__c>) Security.stripInaccessible(AccessType.UPSERTABLE, tempGameList).getRecords();
        List<String> gameName = new List<String>();
        for(My_Games__c temp : gameList){
            gameName.add(temp.Game_Title__c);
        }

        if(gameName.size() != 0){
            List<Game__c> myGames = new List<Game__c>();
            myGames = [SELECT Name, Genre__c, Game_Description__c, Developer__c,Publisher__c FROM Game__c WHERE Name =: gameName];
        	return myGames; 
        }
        else{
            return null;
        }
    }
    
    @AuraEnabled
    public static List<Game__c> getMostPopularGame(){
        //get the game record and get their number 
        
        try{
            List<AggregateResult> gameCount = [SELECT Game__r.Name, COUNT(Id) FROM Game_Orders__c GROUP BY Game__r.Name ORDER BY COUNT(Id) DESC LIMIT 20];
            if(gameCount.size() != 0){
                List<String> gameName = new List<String>();
                for(AggregateResult temp: gameCount){
                    gameName.add(String.valueOf(temp.get('Name')));
                }
                List<Game__c> gameList=[SELECT Name, Genre__c, Game_Description__c, Developer__c,Publisher__c,Game_User_Rating__c,
                                        Price__c FROM Game__c WHERE Name=:gameName LIMIT 20];
                //re-order the game list as found in gameCount
                List<Game__c> gameOrder = new List<Game__c>();
                for(String temp:gameName){
                    for(Game__c gameTemp: gameList){
                        if(temp == gameTemp.Name){
                            gameOrder.add(gameTemp);
                        }
                    }
                }
                return gameOrder;
            }
            else{
                return null;
            }
        }
        catch(Exception e){
            System.debug('There is an Error in the MostPolular game function: '+e.getMessage());
            return null;
        }  
    }
    
    @AuraEnabled
    public static Boolean buyPopularGame(Game__c game){
        Game_Account__c myUser = [SELECT Id, Name, CreatedById, OwnerId  FROM Game_Account__c WHERE  OwnerId= :UserInfo.getUserID() LIMIT 1];
        List<My_Games__c> temp = [SELECT Name FROM My_Games__c WHERE Name=:game.Name AND Game_Account__c=:myUser.Id LIMIT 1];
        System.debug(temp);
        if(temp.isEmpty()){
            My_Games__c myGame = new My_Games__c(Name = game.Name, Game__c=game.Id, Game_Genre__c = game.Genre__c,
                                               Game_Title__c=game.Name, Game_Account__c = myUser.Id);
            insert myGame;
            return false;
        }
        else return true;
    }

}